name: "bromanko's TornBlue"
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["tornblue_left","tornblue_right"]'
      nav: '["vi"]'
      alphas: '["colemakdh-positional"]'
      custom_config: '["#define MIRYOKU_CLIPBOARD_MAC"]'
      kconfig: '["CONFIG_ZMK_POINTING=y"]'
